### ISSUE TITLE
Disconnect not always firing

### ISSUE THREAD

**Issue by kasperrt** [socketio/socket.io#2163]
Hi,

For some reason it seems the disconnect event isn't always firing serverside. I can't seem to find anywhere how to set the heartbeat option on the server, to automaticly disconnect a client when a certain amount of time has passed.

**Comment by dsalcedo** [comment]
```javascript
// Server side
io.on('connection', function (socket) {
  socket.on('disconnect',funtion(socket){
      socket.id
    });
});
```

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by kasperrt** [comment]
I'm already using that code, and that is the event thats not firing.

As said above, the 'disconnect' event, isn't firing, so this isn't solving the issue.

**Comment by dsalcedo** [comment]
can you share the code and give me the stackoverflow link :D ?

**Comment by kasperrt** [comment]
Here is the servercode https://github.com/zoff-music/Zoff/blob/master/server/server.js

**Comment by num-lock** [comment]
I thought I had the exact same annoying issue. Some of my disconnect events just missed out. That usually happened when a client would furiously penetrate the refresh button in his browser or similar scenarios causing the same client to make new connections really fast. **However, after a while** suddenly all the disconnect events appeared. You'd expect them to be there immediately , like they are 99% of the time when you are testing code. But sometimes you just have to wait for a timeout (or whatever happens)

Wait a few minutes and see if you disconnect events will eventually fire then.

**Comment by Lucces** [comment]
@kasperrt I want to know does th issue has been solved?

**Comment by kasperrt** [comment]
Not sure, but think so

-- 

Kasper Rynning-Tønnesen
+97 74 04 27

On Jun 13, 2016 11:51 AM, Lucces <notifications@github.com> wrote:

@kasperrt I want to know does th issue has been solved?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by wagenaartje** [comment]
This is still happening. Basically just spam the F5 button with short intervals.

```
1505142344720 'disconnecting'
1505142344843 'connecting'
1505142344855 'sending info'
1505142345005 'connecting'
```

Notice how the socket is disconnecting, then connecting, and then connecting _again_ without disconnecting first.

**Comment by DGrunk** [comment]
The disconnect function is still not always firing when clients leave; it's really bothersome.

**Comment by darrachequesne** [comment]
@DGrunk if the client is still polling when he leaves, the server-side will rely on a timeout to detect that the client has left (the `pingTimeout / pingInterval` parameters - documented [here](https://github.com/socketio/engine.io#methods-1)), hence the delay before the disconnect event is fired.

**Comment by Linzdigr** [comment]
Is the timeout fires the `disconnect` event? On my side, a basic example with incrementing a counter when client connects and decrement when disconnects left a non-zero value when all clients are gone.

I tried iterating over `IO.sockets` to check the `connected `property and it doesn't seem to reflect the problem.

Note: again, this happens on a small part of connections (I have about 2000 clients simultaneously). It appears to be around 2 or 3% of them.

Any idea?

**Comment by num-lock** [comment]
See https://github.com/socketio/socket.io/issues/2163#issuecomment-136322238

Just wait. After a (pretty long time (read as: minutes, sometimes in the double digits)) they will get a timeout. You don't always immediately get a disconnect every time you press F5. Some are minutes later. Sure this is an issue, but a different one as stated here. Saying there isn't a disconnect for every connect is simply wrong.

**Comment by thepianist2** [comment]
I think this is due to the pingTimeout parameter

**Comment by peterzanetti** [comment]
There has definitely been an ongoing issue for years making disconnect handler unreliable. We use it to resolve all sorts of records about the connection and update state in the application, and we've had to develop backup methods to account for socket io not reliably firing disconnect events (and thusly all code that executes in response to disconnect).

**Comment by darrachequesne** [comment]
@peterzanetti are you able to reliably reproduce?

When using the example [here](https://github.com/socketio/socket.io-fiddle) and refreshing the browser a lot of times, the disconnection seems to always happen:

- either right away if the WebSocket connection was established
- or after a few seconds (up to 45 seconds by default) when the heartbeat mechanism fails

```
current: 0
connect MTY3Ug6wus3TGtDKAAAB
current: 1
disconnect MTY3Ug6wus3TGtDKAAAB due to transport close <-- WebSocket disconnection
current: 0
connect hxp-om1aCV68e6GDAADn
current: 1
current: 1
current: 1
current: 1
current: 1
disconnect hxp-om1aCV68e6GDAADn due to ping timeout <-- heartbeat failure
current: 0
```

Looking into the code, I wasn't able to find some kind of race condition:

- Engine.IO
  - Socket is created there: https://github.com/socketio/engine.io/blob/ce3fe9d80b94297ad64606db6142778c37a8d762/lib/server.ts#L373
  - the heartbeat mechanism is scheduled right away: https://github.com/socketio/engine.io/blob/ce3fe9d80b94297ad64606db6142778c37a8d762/lib/socket.ts#L110
  - then connection is emitted there: https://github.com/socketio/engine.io/blob/ce3fe9d80b94297ad64606db6142778c37a8d762/lib/server.ts#L400
- Socket.IO
  - the connection is caught there: https://github.com/socketio/socket.io/blob/2f9643895207a95e4ee836b6d813163f52036bb9/lib/index.ts#L553
  - and "close" event is being listened to: https://github.com/socketio/socket.io/blob/2f9643895207a95e4ee836b6d813163f52036bb9/lib/client.ts#L91

Knowing the state (`socket.conn.readyState` and `socket.conn.transport.readyState`) of zombie clients would help debugging what happens here.

**Comment by peterzanetti** [comment]
Honestly it is pretty hard for us to trace or debug. All we can do is look at the aftermath and see how much code did not execute on socket disconnect, that should have. We gave up trying to debug it long ago and put back up methods in place to resolve data that is not updated by missed code execution on disconnect.

**Comment by introspection3** [comment]
me too.it's a bug

**Comment by darrachequesne** [comment]
@introspection3 could you please open a new issue with all necessary details? Thanks!
