### ISSUE TITLE
Document type change of Socket#rooms

### ISSUE THREAD

**Issue by shuhei** [socketio/socket.io#2371]
As of 1.4.0, [`Socket#rooms` changed from `Array` to `Object`](https://github.com/socketio/socket.io/pull/2239) but the documents still say that it's an `Array`.

- README.md
- History.md (doesn't mention it)
- The official website

**Comment by mikermcneil** [comment]
cc @darrachequesne
Here's the link to the relevant docs: http://socket.io/docs/server-api/#socket#rooms:array

**Comment by Sammaye** [comment]
I noticed this too when `indexOf` breaks on my code in 1.4.1. The link to the doc is useless since, as stated in the first post, there is no mention of this change.

The code returns object but the doc says array...

**Comment by Sammaye** [comment]
Is this a confirmed change or something that might be reverted?

If we know the answer to that we can change our code to match

**Comment by titoBouzout** [comment]
> We published three minor releases

minor? :o

**Comment by mikermcneil** [comment]
@Sammaye ah- the link to the docs is to make it easier to find and fix.

**Comment by mikermcneil** [comment]
I just popped in to https://github.com/socketio/socket.io-website to have a peek totally forgot the docs content is db-backed (WordPress).  @Sammaye My bad!

@rauchg let me know if there's any other way we can help in the mean time, and thanks for hustling these patches out.

**Comment by Sammaye** [comment]
Sorry yeah, I realised that and deleted my comment :) a bit late at night there

**Comment by mikermcneil** [comment]
@Sammaye feel ya :)

**Comment by nkzawa** [comment]
Fixed in https://github.com/socketio/socket.io/pull/2380. Thanks @shuhei !

**Comment by shuhei** [comment]
@darrachequesne @nkzawa Thanks!

**Comment by CrisLi** [comment]
The link is still incorrect.

http://socket.io/docs/server-api/#socket#rooms:array
