### ISSUE TITLE
navigator is not defined.

### ISSUE THREAD

**Issue by farebord** [socketio/socket.io#2680]
```
var io = require('socket.io')();
  io.on('connection', function(socket) {
    io.emmit('this', {will: 'example'});

    socket.on('disconnect', function() {
      io.emmit('user disconnected');
    })
  });
  io.listen(27965);
```

I tried running this on a Electron compiled app which start a server on a button click. Its shows "navigator is not defined". This code is on main.js (main process).

**Comment by MaffooBristol** [comment]
Hello. Two things:

1. It's `io.emit` not `io.emmit`
2. There's no mention of navigator in your code, are you sure this is where the issue lies?

**Comment by Nibbler999** [comment]
That would be https://github.com/socketio/engine.io-parser/pull/55

**Comment by MaffooBristol** [comment]
Good catch. So is the solution to use a newer s.io?

**Comment by farebord** [comment]
@MaffooBristol @Nibbler999 I'm using 1.4.6 which includes socketio/engine.io-parser#55 fix. 
I've change io.emmit to io.emit, the error is still there. 'navigators is not defined'

**Comment by carpii** [comment]
@farebord I haven't used ElectronReact, but it seems maybe this is the problem rather than socket.io
Check to see if ElectronReact has bundled its own (outdated) socket.io rather than the one you have installed via npm?

Or post the exact file:line in socket.io where the navigator exception is occurring.

**Comment by darrachequesne** [comment]
@farebord Was your issue fixed by https://github.com/socketio/engine.io-parser/pull/55?

**Comment by farebord** [comment]
@darrachequesne no, its still not fixed. It wont work when I package an electron + socket.io app and I try to run it.

**Comment by darrachequesne** [comment]
It seems to work though: https://github.com/darrachequesne/electron-quick-start

Which version of socket.io are you using?

**Comment by darrachequesne** [comment]
@farebord thanks for the feedback!
