### ISSUE TITLE
Setting a timer for a long period of time warning

### ISSUE THREAD

**Issue by rickardinho** [socketio/socket.io#3054]
Hi, I'm getting the following warnings when using socket.io with my React Native project.

I'm on React Native version 0.44.3 
and socket.io-client: 1.5.1

Any ideas of how to solve or is this a bug?  It seems to be slowing my whole app down significantly, as well as producing lots of console warnings.

Here is the error in the console:

Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
console.warn @ index.android.bundle:40843
setTimeout @ index.android.bundle:3412
Socket.onHeartbeat @ index.android.bundle:72517
Emitter.emit @ index.android.bundle:74290
Socket.onPacket @ index.android.bundle:72470
(anonymous) @ index.android.bundle:72336
Emitter.emit @ index.android.bundle:74290
Transport.onPacket @ index.android.bundle:73298
Transport.onData @ index.android.bundle:73294
ws.onmessage @ index.android.bundle:74952
dispatchEvent @ index.android.bundle:13268
(anonymous) @ index.android.bundle:12969
emit @ index.android.bundle:3853
__callFunction @ index.android.bundle:2092
(anonymous) @ index.android.bundle:1950
__guard @ index.android.bundle:2064
callFunctionReturnFlushedQueue @ index.android.bundle:1949
(anonymous) @ debuggerWorker.js:71
index.android.bundle:40843 Remote debugger is in a background tab which may cause apps to perform slowly. Fix this by foregrounding the tab (or opening it in a separate window).
console.warn @ index.android.bundle:40843
(anonymous) @ debuggerWorker.js:25
(anonymous) @ debuggerWorker.js:53

Thanks

**Comment by KingCosmic** [comment]
add
```js
var io = socketio(server, {pingTimeout: 30000});
```  or some other amount it defaults to 85000 which is more then RN likes

**Comment by ikhsanalatsary** [comment]
@KingCosmic not work for me

**Comment by KingCosmic** [comment]
Is your issue the same as the o e here? @ikgsanalatsary

**Comment by juergengunz** [comment]
does not work for me either

**Comment by matthieupinte** [comment]
Same warning... but not working for me either @KingCosmic :/
Thanks for your help ;)

**Comment by imdadahad** [comment]
Facing the same issue, any news?

**Comment by KingCosmic** [comment]
did you try configuring socket timeout

**Comment by matthieupinte** [comment]
@KingCosmic tried with `{ pingTimeout: 30000 }`, `{ timeout: 30000 }` as defined in doc. Do I have to do it server-side or client-side ?

**Comment by ikhsanalatsary** [comment]
@KingCosmic I tried both in server side & RN. But the yellow warning still show

**Comment by KingCosmic** [comment]
Why am I the only one be here ;-; @ikhsanalatsary what is your error exactly and @matthieupinte server side should be fine how are you connecting socket.io to your http server?

**Comment by ikhsanalatsary** [comment]
![screenshot_2017-12-08-09-39-03](https://user-images.githubusercontent.com/5897415/33749633-681fe562-dc01-11e7-8372-bb92a61598cd.png)

and in my React native app:
![screen shot 2017-12-08 at 10 12 32 am](https://user-images.githubusercontent.com/5897415/33749676-9d09435e-dc01-11e7-97f9-2ea85825d4df.png)

dependency: 
 "react": "16.0.0-alpha.12",
 "react-native": "0.48.4",
 "socket.io-client": "2.0.4",

server dependency:
  "socket.io": "~2.0.3",

**Comment by KingCosmic** [comment]
@ikhsanalatsary set the ping timeout server side not client side and it should be fixed

**Comment by KingCosmic** [comment]
That's what fixed it for me anyways

**Comment by hansinhu** [comment]
does not work

**Comment by aprilmintacpineda** [comment]
on the server side do this:

```
const io = socketIO(server, {
  pingTimeout: 30000,
  pingInterval: 30000
});
```

**Comment by jussirantala** [comment]
`(console as any).ignoredYellowBox = [ 'Setting a timer' ];`

**Comment by jamrizzi** [comment]
This fixes the yellow box and the console log. It even fixes it for Expo.

Simply place the following script at the beginning of your codebase.

```js
import { YellowBox } from 'react-native';
import _ from 'lodash';

YellowBox.ignoreWarnings(['Setting a timer']);
const _console = _.clone(console);
console.warn = message => {
  if (message.indexOf('Setting a timer') <= -1) {
    _console.warn(message);
  }
};
```

**Comment by jamrizzi** [comment]
I've encapsulated the previous logic into two npm modules, one for general node/javascript and one for react-native.

The react-native module is compatible with expo apps.

https://github.com/jamrizzi/ignore-warnings
https://www.npmjs.com/package/ignore-warnings
https://github.com/jamrizzi/react-native-ignore-warnings
https://www.npmjs.com/package/react-native-ignore-warnings

You would use it the following way . . .

```js
import ignoreWarnings from 'react-native-ignore-warnings';
ignoreWarnings('Setting a timer');
```

**Comment by darrachequesne** [comment]
As noted above, I think setting `pingTimeout` and `pingInterval` (which currently default to `60000` and  `25000`) should fix the issue.

**Comment by KingCosmic** [comment]
after some more looking around, pingTimeout fixed it on iOS but on android it still showed up but as said above pingInterval might fix that

**Comment by giantss** [comment]
@ikhsanalatsary Hello, Can it be used in the react native project? I plan to use it. Please advise.

**Comment by jamrizzi** [comment]
@giantss can what be used in the react native project?

**Comment by giantss** [comment]
@jamrizzi socket.io

**Comment by ikhsanalatsary** [comment]
Its works after I update socket.io in the server and did
 ```
const io = socketIO(server, {
  pingTimeout: 30000,
  pingInterval: 30000
});
```

As @aprilmintacpineda mentioned

**Comment by giantss** [comment]
@ikhsanalatsary Are you using [socket.io-client](https://github.com/socketio/socket.io-client)?

**Comment by ikhsanalatsary** [comment]
@giantss yes

**Comment by giantss** [comment]
@ikhsanalatsary  thanks,  Could you provide some of the core client-side initialization code? Have you used webscoket?

**Comment by ikhsanalatsary** [comment]
```javascript
const socket = io(api.BASE_API_URL, {
  transports: ['websocket'] // you need to explicitly tell it to use websockets
})

class RootContainer extends PureComponent<Props> {
  // class body
}
```
put it outside on your root component

**Comment by giantss** [comment]
Your reply is very helpful to me, thank you very much.

**Comment by giantss** [comment]
@ikhsanalatsary Hello, do you have encountered the following warning in the integration process?
`Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)`
How do you solve this warning?

**Comment by jamrizzi** [comment]
I'm not sure what the real solution is yet, but you can at least hide the error for now. Refer to my previous comments.

**Comment by giantss** [comment]
@jamrizzi Thank you for your answer, I have seen this solution before, I do not know what better solution

**Comment by jamrizzi** [comment]
@giantss, yeah I wish I had a better answer.

**Comment by darrachequesne** [comment]
@jamrizzi @giantss did you try the answer from @aprilmintacpineda above?

```
const io = socketIO(server, {
  pingTimeout: 5000 // this will be the default starting version 2.1.0 (currently it's 60000)
});
```

**Comment by giantss** [comment]
@darrachequesne I tried this solution but it has no effect. @ikhsanalatsary He also encountered this warning. I don't know if he has solved it perfectly.

**Comment by aprilmintacpineda** [comment]
@giantss That's weird. Can you paste the code of your `server.js` here? at least the ones relevant to `socket.io`. That way we can help you more.

**Comment by giantss** [comment]
@aprilmintacpineda Thank you for your advice.This warning appears in the react native app.

**Comment by aprilmintacpineda** [comment]
@giantss  Yes, it does. Please post the `server.js`. Basically, the reason for the warning is that `socket.io` timer defaults to `80000` (I think, correct me if I'm wrong), react-native hates this. This is not an issue with `socket.io-client`, which is in the frontend, but rather this is an issue with `socket.io`, which is in the backend, and therefore, you need to fix it there.

**Comment by aprilmintacpineda** [comment]
@giantss if you followed my advice above, you should have a code like this on the backend.

```js
// .. other codes

server.listen(9000, () => {
  console.log('Dev server is running on http(s)://localhost:9000.');
  console.log('http(s)://10.0.22:9000 for android');
});

/**
 * socket.io
 */
import socketEvents from './sockets';

const io = socketIO(server, {
  pingTimeout: 30000,
  pingInterval: 30000
});

// .. other codes

io.on('connection', socket => {
  // events
});
```

**Comment by giantss** [comment]
@aprilmintacpineda I use the `server.js` in this [demo](https://github.com/cleverqin/node-websocket-Chatroom)，I tried to modify the fifth line of the demo `server.js` file to the following,
```
 io = require('socket.io')(server, {pingTimeout: 30000,pingInterval: 30000}),
```
then restart the server, the problem still exists.

**Comment by aprilmintacpineda** [comment]
have you done `npm update`?

**Comment by giantss** [comment]
The version used in the demo is `"socket.io": "^2.0.1"`，Do you think there is a relationship with the version?

**Comment by rafser01** [comment]
Thanks @aprilmintacpineda 
It works for me by adding 
```
{
  pingTimeout: 30000,
  pingInterval: 30000
}
```
in server side.

**Comment by ikhsanalatsary** [comment]
@giantss use latest version

**Comment by juergengunz** [comment]
all solutions mentioned here, do not solve this issue for me.

**Comment by kyriakos** [comment]
Unfortunately I have no control over the server side so I can't change the timeout. Why is this a server side issue to start with though?
Is this warning safe to ignore?

**Comment by pentarex** [comment]
for whomever doesn't work, restart you server.... tried like 20 times... stupid me :D

**Comment by sunday58** [comment]
@codejamninja thanks..it fixed it for Android... Plz I want to know all the warnings this api can fix..thanks

**Comment by darrachequesne** [comment]
For future readers: the default `pingTimeout` value was changed from `60000` to `5000` by [this commit](https://github.com/socketio/engine.io/commit/65b1ad1b8a95fb0547ee3f286c1b7da299c7735a), included in `engine.io@3.2.0` & `socket.io@2.1.0`.

So the complete delay (pingTimeout + pingInterval) is now 30s, which is below the RN threshold of 60s.

Note: this value may be a bit too small, as it may cause ping timeouts when uploading big files. Please increase it if needed.

Documentation [here](https://socket.io/docs/v3/server-initialization/#pingTimeout).
