### ISSUE TITLE
Build failed using npm run build on typescript projects

### ISSUE THREAD

**Issue by darwin-morocho** [socketio/socket.io#3891]
**Describe the bug**
I have a backend with express and typescript that use npm as a package manager and I run the next command to build the project `npm run build` that command run the next script `tsc -p .` to build the project.

But I have the next errors
```
node_modules/socket.io/dist/broadcast-operator.d.ts:1:13 - error TS1005: '=' expected.

1 import type { BroadcastFlags, Room, SocketId } from "socket.io-adapter";
              ~

node_modules/socket.io/dist/broadcast-operator.d.ts:1:53 - error TS1005: ';' expected.

1 import type { BroadcastFlags, Room, SocketId } from "socket.io-adapter";
                                                      ~~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/broadcast-operator.d.ts:3:13 - error TS1005: '=' expected.

3 import type { Adapter } from "socket.io-adapter";
              ~

node_modules/socket.io/dist/broadcast-operator.d.ts:3:30 - error TS1005: ';' expected.

3 import type { Adapter } from "socket.io-adapter";
                               ~~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/broadcast-operator.d.ts:4:13 - error TS1005: '=' expected.

4 import type { EventParams, EventNames, EventsMap, TypedEventBroadcaster } from "./typed-events";
              ~

node_modules/socket.io/dist/broadcast-operator.d.ts:4:80 - error TS1005: ';' expected.

4 import type { EventParams, EventNames, EventsMap, TypedEventBroadcaster } from "./typed-events";
                                                                                 ~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/index.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Encoder } from "socket.io-parser";
              ~

node_modules/socket.io/dist/index.d.ts:6:30 - error TS1005: ';' expected.

6 import type { Encoder } from "socket.io-parser";
                               ~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/index.d.ts:8:13 - error TS1005: '=' expected.

8 import type { CookieSerializeOptions } from "cookie";
              ~

node_modules/socket.io/dist/index.d.ts:8:45 - error TS1005: ';' expected.

8 import type { CookieSerializeOptions } from "cookie";
                                              ~~~~~~~~

node_modules/socket.io/dist/index.d.ts:9:13 - error TS1005: '=' expected.

9 import type { CorsOptions } from "cors";
              ~

node_modules/socket.io/dist/index.d.ts:9:34 - error TS1005: ';' expected.

9 import type { CorsOptions } from "cors";
                                   ~~~~~~

node_modules/socket.io/dist/index.d.ts:10:13 - error TS1005: '=' expected.

10 import type { BroadcastOperator, RemoteSocket } from "./broadcast-operator";
               ~

node_modules/socket.io/dist/index.d.ts:10:54 - error TS1005: ';' expected.

10 import type { BroadcastOperator, RemoteSocket } from "./broadcast-operator";
                                                        ~~~~~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/namespace.d.ts:2:13 - error TS1005: '=' expected.

2 import type { Server } from "./index";
              ~

node_modules/socket.io/dist/namespace.d.ts:2:29 - error TS1005: ';' expected.

2 import type { Server } from "./index";
                              ~~~~~~~~~

node_modules/socket.io/dist/namespace.d.ts:4:13 - error TS1005: '=' expected.

4 import type { Client } from "./client";
              ~

node_modules/socket.io/dist/namespace.d.ts:4:29 - error TS1005: ';' expected.

4 import type { Client } from "./client";
                              ~~~~~~~~~~

node_modules/socket.io/dist/namespace.d.ts:5:13 - error TS1005: '=' expected.

5 import type { Adapter, Room, SocketId } from "socket.io-adapter";
              ~

node_modules/socket.io/dist/namespace.d.ts:5:46 - error TS1005: ';' expected.

5 import type { Adapter, Room, SocketId } from "socket.io-adapter";
                                               ~~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/socket.d.ts:4:13 - error TS1005: '=' expected.

4 import type { Client } from "./client";
              ~

node_modules/socket.io/dist/socket.d.ts:4:29 - error TS1005: ';' expected.

4 import type { Client } from "./client";
                              ~~~~~~~~~~

node_modules/socket.io/dist/socket.d.ts:5:13 - error TS1005: '=' expected.

5 import type { Namespace } from "./namespace";
              ~

node_modules/socket.io/dist/socket.d.ts:5:32 - error TS1005: ';' expected.

5 import type { Namespace } from "./namespace";
                                 ~~~~~~~~~~~~~

node_modules/socket.io/dist/socket.d.ts:6:13 - error TS1005: '=' expected.

6 import type { IncomingMessage, IncomingHttpHeaders } from "http";
              ~

node_modules/socket.io/dist/socket.d.ts:6:59 - error TS1005: ';' expected.

6 import type { IncomingMessage, IncomingHttpHeaders } from "http";
                                                            ~~~~~~

node_modules/socket.io/dist/socket.d.ts:7:13 - error TS1005: '=' expected.

7 import type { Room, SocketId } from "socket.io-adapter";
              ~

node_modules/socket.io/dist/socket.d.ts:7:37 - error TS1005: ';' expected.

7 import type { Room, SocketId } from "socket.io-adapter";
                                      ~~~~~~~~~~~~~~~~~~~

node_modules/socket.io/dist/socket.d.ts:8:13 - error TS1005: '=' expected.

8 import type { ParsedUrlQuery } from "querystring";
              ~

node_modules/socket.io/dist/socket.d.ts:8:37 - error TS1005: ';' expected.

8 import type { ParsedUrlQuery } from "querystring";
```

Versions used
```
   "socket.io": "^4.0.1",
    "socket.io-redis": "^6.1.0",
```

**Comment by darwin-morocho** [comment]
Fixed after update my typescript version

**Comment by darrachequesne** [comment]
Hi! That's a good point, I think we should add this somewhere in the documentation :+1: (`import type` syntax was added in TypeScript 3.8)

**Comment by saptarshi007** [comment]
I have the same issue, but even after updating curret typescript version. still facing same errors as mentioned here. Could you please help here?

**Comment by darrachequesne** [comment]
@saptarshi007 that's weird. Could you please check your typescript version with `npm ls typescript`?

**Comment by ithustle** [comment]
@darrachequesne I'm facing the same issue. I'm using `typescript version 4.5.5`

**Comment by bernardarhia** [comment]
> @darrachequesne I'm facing the same issue. I'm using `typescript version 4.5.5`

Have you been able to fix it? I'm also having the same issue with typescript v4.2.3

**Comment by darrachequesne** [comment]
@bernardarhia which version of `socket.io-adapter` are you using?

If it's `2.5.3`, this should be fixed by https://github.com/socketio/socket.io-adapter/commit/ca397f3afe06ed9390db52b70a506a9721e091d8, included in version `2.5.4`. Could you please check?

**Comment by bernardarhia** [comment]
I've found a work around it. I had to install a specific version of socket.io which comes with the socket-adapter.

**Comment by darrachequesne** [comment]
@bernardarhia great :+1: 

For future readers, there was an unsupported syntax (`import { type ... }`) introduced in `socket.io-adapter@2.5.3`, which is only supported starting with `typescript@4.5.0` and which was removed in `socket.io-adapter@2.5.4`.
