### ISSUE TITLE
Types are not installed

### ISSUE THREAD

**Issue by Bazhan4ik** [socketio/socket.io#4621]
**Describe the bug**
Types for `socket.io-parser` and `engine.io-parser` are not installed

**To Reproduce**
Socket.IO server version: `4.5.4`

When compile with typescript it throws these errors:
```
TS7016: Could not find a declaration file for module 'engine.io-parser'. '.../node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`

3 import * as parser from "engine.io-parser";
                          ~~~~~~~~~~~~~~~~~~

TS7016: Could not find a declaration file for module 'engine.io-parser'. '.../node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`

4 import { Packet } from "engine.io-parser";
                         ~~~~~~~~~~~~~~~~~~

TS7016: Could not find a declaration file for module 'socket.io-parser'. '.../node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`

2 import { Packet } from "socket.io-parser";
                         ~~~~~~~~~~~~~~~~~~

TS7016: Could not find a declaration file for module 'socket.io-parser'. '.../node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`

10 import * as parser from "socket.io-parser";
                           ~~~~~~~~~~~~~~~~~~

TS7016: Could not find a declaration file for module 'socket.io-parser'. '.../node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`

11 import type { Encoder } from "socket.io-parser";
                                ~~~~~~~~~~~~~~~~~~

TS7016: Could not find a declaration file for module 'socket.io-parser'. '.../node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`

3 import { Packet } from "socket.io-parser";
                         ~~~~~~~~~~~~~~~~~~
```

Did I do something wrong?
Do I have to install the types manually?

**Comment by darrachequesne** [comment]
Hi! That's weird, the types should be included in the package.

Which OS are you using? Which version of `typescript`?

**Comment by Bazhan4ik** [comment]
Hi

I'm on Windows 11, and I'm using verion `^4.9.4` of typescript

**Comment by darrachequesne** [comment]
That's really weird. The types are declared there:

- https://github.com/socketio/socket.io-parser/blob/0841bd562351c3d45a5288e2adf9707cc8a3131d/package.json#L14
- https://github.com/socketio/engine.io-parser/blob/214182b4f0616a44c18251d9f418a7ca5595dbe4/package.json#L12

And are included in the package:

- https://www.npmjs.com/package/socket.io-parser?activeTab=explore
- https://www.npmjs.com/package/engine.io-parser?activeTab=explore

Not sure what's going wrong here.

**Comment by Bazhan4ik** [comment]
This is probably because of typescript. This is my `tsconfig.json`, and I set `module: NodeNext` which I never used before.
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
  },
  "exclude": [
    "node_modules",
    "web/node_modules",
  ]
}

```
And if module is set to `commonjs` I get no errors.

**Comment by algnor** [comment]
I'm running into the same issue, using commonjs fixes the problem, however a few of the packages i need are pure esm only, so changing to commonjs isn't an alternative.
Here is the log.
```
#0 0.436 > tsc -p api/tsconfig.json && cp -r ./api/src/resources/ ./dist/api/resources/
#0 0.436
#0 3.353 node_modules/engine.io/build/engine.io.d.ts(3,25): error TS7016: Could not find a declaration file for module 'engine.io-parser'. '/app/node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.353   Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`
#0 3.354 node_modules/engine.io/build/transport.d.ts(4,24): error TS7016: Could not find a declaration file for module 'engine.io-parser'. '/app/node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.354   Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`
#0 3.354 node_modules/socket.io/dist/client.d.ts(2,24): error TS7016: Could not find a declaration file for module 'socket.io-parser'. '/app/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.354   Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
#0 3.354 node_modules/socket.io/dist/index.d.ts(10,25): error TS7016: Could not find a declaration file for module 'socket.io-parser'. '/app/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.354   Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
#0 3.354 node_modules/socket.io/dist/index.d.ts(11,30): error TS7016: Could not find a declaration file for module 'socket.io-parser'. '/app/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.354   Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
#0 3.354 node_modules/socket.io/dist/socket.d.ts(3,24): error TS7016: Could not find a declaration file for module 'socket.io-parser'. '/app/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
#0 3.354   Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
------
failed to solve: executor failed running [/bin/sh -c npm run build:server]: exit code: 2
```
and `tsconfig.json`
```
{
  "compilerOptions": {
    "outDir": "../dist/api/",
    "noImplicitAny": true,
    "module": "NodeNext",
    "target": "ES2020",
    "allowJs": true,
    "moduleResolution": "NodeNext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true
  }
}
```

**Comment by jcjp** [comment]
I am on the latest `socket.io` and `@socket.io/cluster-adapter` is this error related? When passing `createAdapter` from `@socket.io/cluster-adapter` to `socket.io` `server.adapter`? This is the error:

```
Argument of type '(nsp: any) => ClusterAdapter' is not assignable to parameter of type 'AdapterConstructor'.
Type '(nsp: any) => ClusterAdapter' is not assignable to type '(nsp: Namespace<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>) => Adapter'.
Type 'ClusterAdapter' is missing the following properties from type 'Adapter': _encode, persistSession, restoreSession
```

Seems like this bug has re-occur: https://github.com/socketio/socket.io/issues/3796.

**Comment by igorls** [comment]
Just submitted PRs to fix this on socket.io and engine.io

Tested with the following config:

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ESNext",
    "sourceMap": true,
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by javaarchive** [comment]
I was able to downgrade to `4.5.4` to solve the issue temporarily since I was unable to install the above PR since installing from github excludes the built "dist" directory.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/d0b22c630208669aceb7ae013180c99ef90279b0, included in version `4.6.1`.

@igorls thanks a lot for your work on this.

Please reopen if needed.

**Comment by jcjp** [comment]
Yeah on version 4.6.1 still getting the same error is there something wrong with our implementation of running a client websocket?:

```JavaScript
❯ npm list socket.io
<app_directory>
`-- socket.io@4.6.1
```

```JavaScript
#0 12.97 app/Services/Ws.ts:25:23 - error TS2345: Argument of type '(nsp: any) => ClusterAdapter' is not assignable to parameter of type 'AdapterConstructor'.
#0 12.97   Type '(nsp: any) => ClusterAdapter' is not assignable to type '(nsp: Namespace<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>) => Adapter'.
#0 12.97     Type 'ClusterAdapter' is missing the following properties from type 'Adapter': _encode, persistSession, restoreSession
#0 12.97
#0 12.97 25       this.io.adapter(createAdapter())
#0 12.97                          ~~~~~~~~~~~~~~~
#0 12.97
#0 12.97
#0 12.97 Cannot complete the build process as there are typescript errors. Use "--ignore-ts-errors" flag to ignore Typescript errors
#0 12.97 [ info ]  cleaning up "./build" directory
```

```JavaScript
// socket.ts
import {Server} from 'socket.io'
import {createAdapter} from '@socket.io/cluster-adapter'
import {setupWorker} from '@socket.io/sticky'
...

class ClientWS {
  public srv: Server

  public boot() {
    ...
    this.srv = new Server(AdonisServer.instance!, {
      path: <path>,
      cors: <cors>
    })

    this.srv.adapter(createAdapter())
    setupWorker(this.srv)
  }
}

export default new ClientWS()
```

**Comment by darrachequesne** [comment]
@jcjp this should be fixed in `@socket.io/cluster-adapter@0.2.2`: https://github.com/socketio/socket.io-cluster-adapter/releases/tag/0.2.2

**Comment by maikelRAOW** [comment]
I too still have the same problem on `4.6.1.`

**Comment by leviathanbadger** [comment]
I have a slightly different error as @Metapyziks, but I'm pretty sure it's the same root cause:

```
node_modules/engine.io/build/engine.io.d.ts(3,25): error TS7016: Could not find a declaration file for module 'engine.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`
node_modules/engine.io/build/socket.d.ts(5,25): error TS7016: Could not find a declaration file for module 'engine.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`
node_modules/engine.io/build/transport.d.ts(4,24): error TS7016: Could not find a declaration file for module 'engine.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/engine.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/engine.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'engine.io-parser';`
node_modules/socket.io/dist/client.d.ts(2,24): error TS7016: Could not find a declaration file for module 'socket.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
node_modules/socket.io/dist/index.d.ts(10,25): error TS7016: Could not find a declaration file for module 'socket.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
node_modules/socket.io/dist/index.d.ts(11,30): error TS7016: Could not find a declaration file for module 'socket.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
node_modules/socket.io/dist/socket.d.ts(3,24): error TS7016: Could not find a declaration file for module 'socket.io-parser'. 'C:/Users/brand/source/repos/github/leviathanbadger/shared-notes-socketio/api/node_modules/socket.io-parser/build/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
```

This is my tsconfig.json:

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "outDir": "dist",
    "removeComments": true,
    "target": "ES6",
    "strict": true,
    "sourceMap": true,
    "module": "Node16",
    "moduleResolution": "node16",
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true
  },
  "include": ["./src/**/*.ts"],
  "exclude": [
    "node_modules/**/*"
  ]
}
```

Node version v18.15.0
NPM version 9.5.0
Typescript version 5.0.3
Socket.io version 4.6.1

**Comment by brettz9** [comment]
I see there have been some fix commits--can these be published if they resolve the issue?

**Comment by kettanaito** [comment]
The type definitions for the CommonJS target of this library seem to be broken:

<img width="552" alt="Screenshot 2023-05-17 at 20 12 31" src="https://github.com/socketio/socket.io/assets/14984911/b62db1d4-e349-4e1e-a1d9-8b1bb0bbee39">

There are no type definitions in the `/cjs/` directory, which is a mistake. Any dependency resolving `socket.io-parser` as CommonJS will get no type definitions, and the entire package will be annotated as `any`. 

## How to fix this?

You have two options to fix this:

### Option 1: Reference `/esm/` types from `cjs/package.json`

This is a great option if the build output is identical between the CJS and ESM targets of this library. If it is, simply adding `{ "types": "../esm/index.d.ts" }` to `/cjs/package.json` will solve the problem and everyone will be happy. 

### Option 2: Mirror type definitions in `/cjs/`

If there's any concern that the build outputs may not be identical, consider emitting another set of `*.d.ts` files alongside the `/cjs/` build. 

I can help with either solutions just let me know which one you prefer.

**Comment by darrachequesne** [comment]
@kettanaito thanks for the detailed analysis :+1: 

> If it is, simply adding `{ "types": "../esm/index.d.ts" }` to `/cjs/package.json` will solve the problem and everyone will be happy.

So if I'm understanding correctly, the bundler does understand `{ "types": "../esm/index.d.ts" }` in `./build/cjs/package.json` but not `{ "types": "./build/esm/index.d.ts" }` in `./package.json`, is that correct?

> This is also the behavior on some modern bundlers as well.

Out of curiosity, which bundler has this behavior?

**Comment by kettanaito** [comment]
@darrachequesne, yes, you are correct. At least, this is the behavior I'm getting using TypeScript 5.0 in some of my open-source projects. I've gone through an extensive implementation of ESM+TS recently for some of my projects and know firsthand how painful it is to get this right for every consumer.

**Comment by 24thsaint** [comment]
Hello, I am also experiencing this now on our CI build.

```
node_modules/@types/socket.io/index.d.ts(20,68): error TS7016: Could not find a declaration file for module 'socket.io-parser'. '/home/dev_ops/builds/mSJ5VfCs/0/XXX/YYY/node_modules/socket.io-parser/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socket.io-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-parser';`
```

My devDependencies have:
```
"@types/socket.io-parser": "^3.0.0",
```

And tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "outDir": "./lib",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true
  },
  "exclude": [
    "test",
    "client",
    "uploads"
  ],
  "ts-node": {
    "files": true
  },
  "files": [
    "index.d.ts"
  ]
}
```

**Comment by darrachequesne** [comment]
@kettanaito we went for option 2 in https://github.com/socketio/socket.io-parser/commit/dcc70d9678ac896de08294d6e8d668be6a68680a, included in `socket.io-parser@4.2.3`. Could you please check if that fixes the issue?

@24thsaint the types are now included in the package, there should be no need for the `@types/..` installation. Which version of `typescript` / `socket.io` are you using?
