### ISSUE TITLE
Argument of type '(nsp: any) => RedisAdapter' is not assignable to parameter of type 'AdapterConstructor' socket.io version 4.6.0

### ISSUE THREAD

**Issue by EternalC0der** [socketio/socket.io#4624]
**The bug**
I've been using `@socket.io/redis-adapter @8.1.0` with `socket.io @4.5.4` without any issues.
Now that I upgraded to socket.io `4.6.0` it suddenly stopped working and I'm getting an error.

As it is mentioned in the documents (https://socket.io/docs/v4/redis-adapter/),
This is how my code looks like (simplified for the sake of this issue):
```ts
// Typescript
const pubClient = createClient({ url: "redis://localhost:6379" });
const subClient = pubClient.duplicate();

await Promise.all([pubClient.connect(), subClient.connect()]).catch((e) => {
    console.log(`${chalk.hex(pallette.red)('Redis error:')}`, e.message || e)
})

io.adapter(createAdapter(pubClient, subClient)) // <= Error at this line
```

And I'm getting an error with `io.adapter(createAdapter(pubClient, subClient))`:
```
Argument of type '(nsp: any) => RedisAdapter' is not assignable to parameter of type 'AdapterConstructor'.
  Type '(nsp: any) => RedisAdapter' is not assignable to type '(nsp: Namespace<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>) => Adapter'.
    Type 'RedisAdapter' is missing the following properties from type 'Adapter': _encode, persistSession, restoreSession
 ```

**To Reproduce**
Example in the docs (https://socket.io/docs/v4/redis-adapter/) with latest versions of  `@socket.io/redis-adapter`, `socket.io`, `redis` and typescript gives a type error.

**Platform:**
 - Device: Desktop
 - OS: Windows 11
 - Nodejs: 16.19.0

**Comment by darrachequesne** [comment]
Hi! It seems you have two different versions of the `socket.io-adapter` package, which is included by both `socket.io` and `@socket.io/redis-adapter`. Could you please check?

```
$ npm ls socket.io-adapter
```

We have tried to fix this in version `@socket.io/redis-adapter@8.1.0`, with https://github.com/socketio/socket.io-redis-adapter/commit/f07ff7bd33817ac14d8d87ba55225e7936469429, but it does not seem to be sufficient.

As a workaround, could you try running `npm dedupe`?

**Comment by quipo** [comment]
having the same issue with `@socket.io/mongo-adapter@0.2.1`

**Comment by darrachequesne** [comment]
@quipo this should be fixed in latest release of the MongoDB adapter: [`0.3.0`](https://github.com/socketio/socket.io-mongo-adapter/releases/tag/0.3.0)

**Comment by faradaytrs** [comment]
Yeah not fixed

**Comment by jcjp** [comment]
> I'm having the same issue with `@socket.io/cluster-adapter@0.2.1` too.

Same I tried running `npm dedupe` but still have the same issue also tested the latest socket.io version `4.6.1`, I have some details on this closed issue. https://github.com/socketio/socket.io/issues/4621#issuecomment-1480537087.

```JavaScript
+-- @socket.io/cluster-adapter@0.2.1
| `-- socket.io-adapter@2.4.0
`-- socket.io@4.6.1
  `-- socket.io-adapter@2.5.2
```

**Comment by darrachequesne** [comment]
For future readers:

We have added `socket.io-adapter` in the list of peer dependencies of the other adapters, in order to match the version which is imported by the `socket.io` package:

- [@socket.io/redis-adapter@8.1.0](https://github.com/socketio/socket.io-redis-adapter/releases/tag/8.1.0)
- [@socket.io/mongo-adapter@0.3.0](https://github.com/socketio/socket.io-mongo-adapter/releases/tag/0.3.0)
- [@socket.io/postgres-adapter@0.3.1](https://github.com/socketio/socket.io-postgres-adapter/releases/tag/0.3.1)
- [@socket.io/cluster-adapter@0.2.2](https://github.com/socketio/socket.io-cluster-adapter/releases/tag/0.2.2)

So this issue does not happen in the future. Please reopen if needed!

**Comment by fernandoiwamoto** [comment]
I think this is back, I got this error:
Argument of type '(nsp: any) => RedisAdapter' is not assignable to parameter of type 'AdapterConstructor'.
  Type '(nsp: any) => RedisAdapter' is not assignable to type '(nsp: Namespace<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>) => Adapter'.
    Type 'RedisAdapter' is missing the following properties from type 'Adapter': nsp, rooms, sids, encoder, and 27 more.
    
   my packages:
   "dependencies": {
....
    "@socket.io/redis-adapter": "^8.2.1",
    "ioredis": "^5.3.2",
    "redis": "^4.6.7",
    "socket.io": "^4.7.1",
    "typescript": "^5.1.6"
  },
  "devDependencies": {
....
    "@types/node": "^20.4.1",
    "@types/redis": "^4.0.11",
    "@typescript-eslint/eslint-plugin": "^5.61.0",
    "@typescript-eslint/parser": "^5.61.0",
    "eslint": "^8.44.0",
    "jest": "^29.6.1",
    "mock-knex": "^0.4.12",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1"
  }

by copying any example of https://socket.io/docs/v4/redis-adapter/
